site_name: "CMU 17-356: Software Engineering for Startups"

theme:
  name: material
  custom_dir: overrides
  logo:
  favicon: assets/favicon.ico
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - announce.dismiss

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - tables
  - toc:
      title: On This Page
      toc_depth: 4
      permalink: true

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - markdownextradata

nav:
  - Home: index.md
  - Overview: overview.md
  - Syllabus: syllabus.md
  - Teamwork Practices: teamwork.md
  - Staff: staff.md
  - Assignments: # assignments/index.md # Dummy home page; remove once we start adding assignments below
       - Homework 1: assignments/HW1.md
  #    - Homework 2: 'https://github.com/CMU-17-356/cmu-17-356.github.io/raw/refs/heads/main/docs/assignments/hw2.pdf'
  #    - Homework 3: assignments/hw3-25.md
  #    - Homework 4: assignments/hw4-25.md
  #    - Homework 5: assignments/hw5-25.md
  #    - Final Project - Team Sprint 1: assignments/FP1.md
  #    - Final Project - Team Sprint 2: assignments/FP2.md
  #    - Final Project - Team Sprint 3: assignments/FP3.md
  - Recitations: recitations/index.md # Dummy home page; remove once we start adding recitations below
  #    - Recitation 2: recitations/reci2-viability-analysis.md
  #    - Recitation 2: recitations/reci2-nodejs.md
  #    - Recitation 3: recitations/reci3-react.md
  #    - Recitation 4: recitations/reci4-testing.md
  #    - Recitation 5: recitations/reci5-docker-kubernetes.md
  #    - Recitation 6: recitations/reci6-databases-storage.md
  #    - Recitation 7: recitations/reci7-mobile-react-native.md
  #    - Recitation 8: recitations/reci8-responsive-sites.md
  #    - Recitation 9: recitations/reci9-react-native.md
  #- Dronuts:
  #    - Overview: dronuts.md
  #    - Design Assets: project/brand.md
  #    - Node.JS: project/node_js.md
  #    - Credit API: project/credit_api.md
  #    - Drone API: project/drone_api.md
  #    - UI Development: project/ui.md
  #    - Docker: project/docker.md
  #    - Deployment: project/deployment.md
  - Project: #project/index.md # Dummy home page; remove once we start adding project docs below
       - Project 0 Team Contract: project/p0.md
  #    - Project 1 Product Specification: project/p1.md
  #    - Project 2 Implementation Sprint: project/p2.md
  #    - Project 3 Implementation Sprint: project/p3.md
  #    - Project 4 Implementation Sprint: project/p4.md
  #    - Project 5 Final Presentation: project/p5.md
